name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies (Windows)
        run: choco install -y nsis

      - name: Install Rust & Required Targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies (Using npm)
        run: npm install --legacy-peer-deps
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"  # Prevents out-of-memory errors

      - name: Install Tauri CLI
        run: npm install @tauri-apps/cli -g

      - name: Build Tauri App
        run: npx tauri build --verbose

      - name: Generate Update Metadata
        run: npx tauri updater generate

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/bundle/

      - name: Upload Update Metadata
        uses: actions/upload-artifact@v4
        with:
          name: latest.json
          path: src-tauri/target/release/latest.json

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/latest.json
          token: ${{ secrets.GITHUB_TOKEN }}
